import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {tangent,angleDeg,sub,unit,length,dot,cross,diskClearance,segmentsCross,flattenCubic,evaluate} from './geometry.mjs';
import {solve,zeroPositions,withinBounds} from './solver.mjs';
import {loadInputs,makeScenario,sha} from './scenarios.mjs';
import {generate,RESULT_PATH} from './generate.mjs';
const close=(a,b,eps=1e-8)=>assert.ok(Math.abs(a-b)<=eps,`${a} vs ${b}, eps ${eps}`);
const data=JSON.parse(fs.readFileSync(RESULT_PATH,'utf8'));
test('Tangentit: kolme analyyttistä referenssiä sekä molempien haarojen residuaalit',()=>{
 const S={x:0,y:0};for(const y of [3,0,5])for(const branch of [-1,1]){const C={x:100,y},T=tangent(S,C,branch),u=unit(sub(T,S));close(length(sub(T,C)),3);close(dot(u,sub(T,C)),0);close(cross(u,sub(C,S)),-branch*3);const closed=Math.abs(Math.atan2(y,100)+branch*Math.asin(3/Math.hypot(100,y)))*180/Math.PI;close(angleDeg({x:1,y:0},u),closed);}
 close(angleDeg({x:1,y:0},sub(tangent(S,{x:100,y:3},-1),S)),0);
 assert.equal(tangent(S,{x:2,y:0},1),null);assert.equal(tangent(S,{x:100,y:0},0),null);
});
test('Levyn containment tarkistaa koko kiekon ja käyrätoleranssin',()=>{const poly=[{x:0,y:0},{x:20,y:0},{x:20,y:20},{x:0,y:20}];assert.ok(diskClearance({x:10,y:10},7.25,poly)>0);assert.ok(diskClearance({x:7.25,y:10},7.25,poly)<0);assert.ok(diskClearance({x:-1,y:10},.2,poly)<0);const arc=flattenCubic({x:0,y:0},{x:0,y:20},{x:20,y:20},{x:20,y:0});assert.ok(arc.length>20);});
test('Jänteiden risteys ja samansuuntaiset / päällekkäiset reunatapaukset',()=>{assert.ok(segmentsCross({x:0,y:0},{x:10,y:10},{x:0,y:10},{x:10,y:0}));assert.equal(segmentsCross({x:0,y:0},{x:10,y:0},{x:0,y:1},{x:10,y:1}),false);assert.ok(segmentsCross({x:0,y:0},{x:10,y:0},{x:5,y:0},{x:12,y:0}));});
function oracleProblem(){const N=6,e=unit({x:25,y:7}),n={x:-e.y,y:e.x};const A={x:30,y:-23.5};return {N,A,e,n,L:180,seed:Array.from({length:N},(_,i)=>20+25*i),polygon:[{x:-20,y:-80},{x:300,y:-80},{x:300,y:150},{x:-20,y:150}],strings:Array.from({length:N},(_,i)=>({S:{x:0,y:i*7},B:{x:-600,y:i*7}}))};}
test('Solver löytää tunnetun kelvollisen 0° ratkaisun; väärä haara ei peri nollaa',()=>{const p=oracleProblem(),s=solve(p,1).solution;assert.ok(s.valid);close(s.objective[0],0);const z=zeroPositions(p,s.offset,1);assert.ok(withinBounds(p,z));const wrong=evaluate(p,z,s.offset,-1);assert.ok(wrong.objective[0]>1);});
test('Virheellinen järjestys, vieras pylväs, kääntyvä kieli ja liian pieni lapa hylätään',()=>{const p=oracleProblem(),t=zeroPositions(p,12,1);const reversed=evaluate(p,[...t].reverse(),12,1);assert.ok(reversed.errors.includes('Virittimien järjestys vaihtuu'));const overlapping=evaluate(p,[t[0],t[0]+1,...t.slice(2)],12,1);assert.ok(overlapping.errors.includes('Aluslevyt osuvat toisiinsa'));const backwards={...p,strings:p.strings.map(s=>({...s,B:{x:600,y:s.S.y}}))};assert.ok(evaluate(backwards,t,12,1).errors.includes('Kieli kulkee taaksepäin'));assert.equal(data.negativeCase.result.valid,false);assert.ok(data.negativeCase.result.errors.includes('Aluslevy ylittää lavan reunan'));
 const hit={...p,strings:[{S:{x:0,y:0},B:{x:-600,y:0}},{S:{x:0,y:20},B:{x:-600,y:20}}],N:2,A:{x:20,y:-3},e:{x:1,y:0},n:{x:0,y:1},seed:[80,30]};assert.ok(evaluate(hit,[80,30],0,1).errors.includes('Kieli osuu toiseen pylvääseen'));
});
test('12 skenaariota: oikeat vendor-kontaktit, kasvu, kulma ja satulan G1-liitos',async()=>{const inputs=await loadInputs();assert.equal(data.cases.length,12);for(const saved of data.cases){const p=makeScenario(inputs,saved.N,saved.spacing,saved.neck);assert.deepEqual(saved,p.id===saved.id?{...p,layouts:saved.layouts}:null);const scale=1+(p.N-6)*25/p.transform.referenceEdgeLengthMm;close(p.transform.shapeScale,scale);close(Math.sin(p.transform.edgeAngleDeg*Math.PI/180),p.params.stringSpanNut/((p.N-1)*25));assert.equal(p.strings.length,p.N);for(const [key,seg,control] of [['top',p.segments[0],0],['bottom',p.segments.at(-1),1]]){const anchor=p.join[key],end=key==='top'?seg.start:seg.end;assert.deepEqual(anchor,end);const direction=p.join[key==='top'?'dirTop':'dirBottom'];close(cross(direction,unit(sub(seg.control[control],anchor))),0);assert.ok(dot(direction,sub(seg.control[control],anchor))>0);}}});
test('Kaikki 24 layoutia: riippumaton kulma/haara-auditointi, rajat ja tiheän alijoukon vertailu',()=>{for(const p of data.cases)for(const l of p.layouts){const s=l.solution;assert.equal(l.status,'found',p.id+' branch '+l.branch);assert.ok(s.valid);assert.ok(withinBounds(p,s.positions));assert.ok(s.minWasherClearanceMm>=0);assert.ok(s.minOtherPostClearanceMm>=.005);assert.ok(s.minPitchMm>=14.505);assert.equal(s.fullM6FitStatus,'unverified');const angles=[];for(const q of s.strings){const u=unit(sub(q.S,q.B)),w=unit(sub(q.T,q.S));close(length(sub(q.T,q.C)),3);close(dot(w,sub(q.T,q.C)),0);close(cross(w,sub(q.C,q.S)),-l.branch*3);assert.ok(dot(u,w)>0);const angle=Math.acos(Math.max(-1,Math.min(1,dot(u,w))))*180/Math.PI;close(q.angleDeg,angle,2e-6);angles.push(q.angleDeg);}close(Math.max(...angles),s.objective[0]);close(angles.reduce((a,b)=>a+b,0),s.objective[1]);if(l.reference.best){assert.ok(s.objective[0]<=l.reference.best.objective[0]+1e-6,p.id+' reference max angle');if(Math.abs(s.objective[0]-l.reference.best.objective[0])<1e-8)assert.ok(s.objective[1]<=l.reference.best.objective[1]+1e-6);}}});
test('Input-hashit ja deterministinen koko tulos toisella ajolla',async()=>{for(const [p,hash] of Object.entries(data.sourceHashes))assert.equal(sha(p),hash);assert.deepEqual(await generate(),data);});
test('Tuotantosovelluksen 56 lähde/config-tiedostoa säilyivät',()=>{const baseline=JSON.parse(fs.readFileSync('tmp/headstock-lab-source-baseline.json','utf8'));assert.equal(Object.keys(baseline).length,56);for(const [p,h] of Object.entries(baseline))assert.equal(sha(p),h,p);});

test('Lähes rinnakkainen rivi ei tuota äärettömiä hyväksyttyjä paikkoja',()=>{const p={...oracleProblem(),e:{x:1,y:0},n:{x:0,y:1}};assert.ok(zeroPositions(p,12,1).every(Number.isNaN));assert.equal(withinBounds(p,zeroPositions(p,12,1)),false);const result=solve(p,1);assert.ok(result.solution.positions.every(Number.isFinite));});
